// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnoosutnsepzxsqgguge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRub29zdXRuc2VwenhzcWdndWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMjA2MTgsImV4cCI6MjA2MTc5NjYxOH0.axZc0z3jerNTwuextSjDJLk1r88Xh02MbnCZaLA8y1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);